# Generated by Django 2.1.5 on 2019-02-18 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20190210_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
